---
title: "KPMG Thesis Project"
output: html_document
---

# Data Reading:
```{r}
library(readr)

#uncomment when you want to read the data from fresh
#Data <- read_delim("E:/KPMG/Data/KPMGDT.csv",",", escape_double = FALSE, trim_ws = TRUE)
```
# Data Prepration
```{r}
Data$CreditRating <- as.factor(Data$CreditRating)
Data$InterestType <- as.factor(Data$InterestType)
Data$MortgageType <- as.factor(Data$MortgageType)
Data$NewLoan <- as.factor(Data$NewLoan)
Data$ProbationaryLoans <- as.factor(Data$ProbationaryLoans)
Data$LTVCategory <- as.factor(Data$LTVCategory)
Data$InArrears <- as.factor(Data$InArrears)
Data$County <- as.factor(Data$County)
Data$DefaultedLoans <- as.factor(Data$DefaultedLoans)
```

# Data Stats
```{r}

dim(Data)
names(Data)
summary(Data)
```


#Subsetting Train and Test Datasets
```{r}
set.seed(1234)
dataPartition = sample(2,nrow(Data),replace=TRUE,prob=c(0.7,0.3))
trainData <- Data[dataPartition ==1,]
testData <- Data[dataPartition ==2,]
```

## Vizualization of Ireland property price market

```{r}
## Load the library
library(dplyr)
library(maps)
library(reshape2)
library(leaflet)
library(ggplot2)
library(ggmap)
library(gridExtra)
library(htmlwidgets)
library(readr)
ResMortgage <- data.frame(Data)
weatherIcon <- makeIcon(
                         iconUrl = "./fig/weather.png",
                         iconWidth = 30, 
                         iconHeight = 30
                        )

popupInfo <- paste(ResMortgage[['ContractRef']], 
                   ", ", 
                   ResMortgage[['LoanBalance']],
                   "<br>", 
                   "Average January Temp in F:  ",
                   ResMortgage[['DefaultedLoans']],
                   "<br>", 
                   "Credit Rating:  ",
                   ResMortgage[['CreditRating']],
                   "<br>", 
                   "LTV:  ",
                   ResMortgage[['LTV']],
                   "<br>", 
                   "Property Value:  ",
                   ResMortgage[['PropertyValue']],
                   sep='')


MapDisplay <- leaflet(ResMortgage) %>% 
                          setView(-93.65, 42.0285, zoom = 4) %>%
                                 addTiles() %>%
                                      addMarkers(Data$AddressLongitude, Data$AddressLatitude, popup= ~ popupInfo,
                                      options = popupOptions(closeButton = TRUE),
                                      clusterOptions = markerClusterOptions(), 
                                      icon = weatherIcon)
MapDisplay
#saveWidget(MapDisplay, file="MapDisplay.html")

```
####################################
#
#Update this part
#
#####################################

```{r}
library(lubridate)
library(ggplot2)
library(dplyr)
library(stringr)
library(caret)
library(rpart)
library(rattle)
library(ROSE)
library(ROCR)
library(MASS)
library(ipred)
library(plyr)
library(rpart.plot)
library(readr)
levels.default(testData$DefaultedLoans)
table(testData$DefaultedLoans, testData$CreditRating)
ggplot(testData, aes(x = testData$LoanBalance)) +geom_histogram(aes(fill = CreditRating)) +facet_wrap(~DefaultedLoans, ncol=1)

```
```{r}
index = createDataPartition(y = testData$DefaultedLoans, p = 0.90)[[1]]
loans.sample <- testData[-index,]
ggplot(loans.sample, aes(x = testData$CreditRating, y = testData$CreditRatingMovement)) + geom_point(aes(color = testData$MortgageYears))

```

```{r}
#Decision Tree
index = createDataPartition(y = mydata$DefaultedLoans, p = 0.9)[[1]]
mydata.test <- mydata[-index,]
mydata.train <- mydata[index,]
mydata.rpart.0 <- rpart(DefaultedLoans ~ ., data = mydata.train)

mydata.rpart.1 <- rpart(DefaultedLoans ~ . , data = mydata.train, 
                      control=rpart.control(minsplit=10, minbucket = 3, cp=0.0006))


fancyRpartPlot(mydata.rpart.0)
```

```{r}
predictions.1 <- (predict(mydata.rpart.1, mydata.test, type = "class"))
confusionMatrix(predictions.1, mydata.test$DefaultedLoans)
```

```{r}
#Confusion Matrix
mydata.oversampled <- ovun.sample(DefaultedLoans ~ ., data = mydata.train, method = "over", N = 52410, seed = 13)$data

table(mydata.oversampled$DefaultedLoans)
tune <- data.frame(0.001)
colnames(tune) <- "cp"
tr_control <- trainControl(method = "cv",number = 10, verboseIter = TRUE)
mydata.rpart.oversampled <- train(DefaultedLoans ~., data = mydata.oversampled, method = "rpart", trControl = tr_control, tuneGrid = tune, control=rpart.control(minsplit=10, minbucket = 3))

```
```{r}
#ROC Line Plot
roc.curve(mydata.test$DefaultedLoans, predict(mydata.rpart.1, mydata.test, type = "prob")[,1], plot = TRUE)
```
#Model for Tableau
```{r}
mydata <- read.csv("E:/KPMG/Data/Prep/Sample1_3.csv")
lrmodel <- glm(DefaultedLoans ~ CreditRating + LoanBalance + PropertyValue, data = mydata, family = "binomial");
save(lrmodel, file = "mymodel.rda")

```

```{r}
load("mymodel.rda")
prob <- predict(lrmodel, newdata = mydata1, type = "response")
plot(prob,mydata1$CreditRating)

```


## Decision tree using Tree()
```{r}
library(C50)
library(tree)
library(rpart)
data.rp <- rpart(DefaultedLoans~., data=trainData)

```
```{r}
library(rpart)
library(rattle)					# Fancy tree plot
library(rpart.plot)				# Enhanced tree plots
library(RColorBrewer)				# Color selection for fancy tree plot
library(party)					# Alternative decision tree algorithm
library(partykit)				# Convert rpart object to BinaryTree
library(caret)
print(data.rp)
prp(data.rp)
```


#Decision Tree for Tableu
```{r}
#Decision Tree for Tableu
library(rpart)
library(rattle)					# Fancy tree plot
library(rpart.plot)				# Enhanced tree plots
library(RColorBrewer)				# Color selection for fancy tree plot
library(party)					# Alternative decision tree algorithm
library(partykit)				# Convert rpart object to BinaryTree
library(caret)
fit <- rpart(DefaultedLoans ~ County+LoanBalance + PropertyValue+ CreditRating+ AnnualPYMT,method = "class",data=testData, control =  rpart.control(minisplit=15,cp = 0.001))

save(fit, file = "myclassificationtree.rda")
print(fit)
prp(fit)
tree.1 <- fit
fancyRpartPlot(tree.1)
```
# Regression Trees
```{r}
library(tree)
tree.model <- tree(DefaultedLoans~., data=testData)
plot(testData$AddressLongitude, testData$AddressLatitude, col=grey(10:2/11)[testData$PropertyValue], pch=20, xlab="Longitude",ylab="Latitude")
```

